version: 2.1

jobs:
    build:
        working_directory: ~/app
        docker:
            - image: vdtn359/node-pnpm:14-alpine
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install
                  command: |
                      npm run setup
                      pnpm install --frozen-lockfile --unsafe-perm
            - save_cache:
                  key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - /root/.pnpm-store/v3
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    test:
        docker:
            - image: vdtn359/node-pnpm:14-alpine
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Test
                  command: |
                      npm run test:coverage
                      npm run publish:coverage
            - store_artifacts:
                  path: coverage
                  destination: coverage
    release:
        docker:
            - image: vdtn359/node-pnpm:14-alpine
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Release
                  command: |
                      printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
                      npm config set access public
                      mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
                      pnpm config set workspace-concurrency 1
                      npm run release
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - release:
                  requires:
                      - build
                      - test
                  filters:
                      branches:
                          only:
                              - master
